### ISSUE TITLE
Multiple CIDR with same mask length fail in `match_bin`

### ISSUE THREAD

**Issue by EpicEric** [iresty/lua-resty-ipmatcher#18]
We are using this module through the [Kong ip-restriction plugin](https://github.com/api7/lua-resty-ipmatcher/blob/211e0d2eb8bbb558b79368f89948a0bafdc23654/resty/ipmatcher.lua), which calls `ip:match_bin(ngx.var.binary_remote_addr)`. We have noticed that multiple networks with same CIDR length (in our case, IPv6 /64) would cause only the first one to match, and the other(s) to be ignored.

For example, with the addresses `2001:db8:0:7::/64, 2001:db8:0:1::/64`, the address `2001:db8:0:1:2::3` will not match. But if the order is reversed (`2001:db8:0:1::/64, 2001:db8:0:7::/64`), it matches.

**Comment by membphis** [comment]
@spacewander do you have time to confirm this issue? it seems to be a bug

**Comment by spacewander** [comment]
Should be solved by lua-resty-ipmatcher 0.6.1
